name: virprof
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal >=6.2
  - click
  - click-completion
  - ruamel.yaml >0.15
  - drmaa
  - pandas >=0.20
  - openpyxl
  - coloredlogs
  - setuptools_scm >=3.4
  - setuptools >=42
  - wheel
  - xdg
  - tqdm >=4.21
  - aiohttp
  - networkx >=2.0
  - pygraphviz
  - pip
  - pip:
    - git+https://github.com/epruesse/ymp@development

  - graph-tool >=2.34
  - biopython
  - click
  - tqdm
  - networkx > 2
  - requests
